config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'users/my_page' => 'users#show', as: 'my_page'
  resources :users, only: [:edit, :update]

  resources :albums, only: [:show, :create, :destroy]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :albums, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)

    @album.user_id = current_user.id
    @album.save
    redirect_to @album
  end

  def destroy
  end

  private

  def album_params
    params.permit(:album_id, :artist_name, :spotify_url, :album_name, :image_url, :itunes_url, :youtube_url, :soundcloud_url, :bak_artist_name, :bak_image_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    gon.grant_type = ENV['SP_GRANT_TYPE']
    gon.client_secret = ENV['SP_CLIENT_SECRET']
    gon.client_id = ENV['SP_CLIENT_ID']
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(current_user.id)
    @albums = @user.albums
  end


  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image_id)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/show.html.erb
<input type="hidden" id="bg-image" value="<%= @album.image_url %>">
<input type="hidden" id="url-itunes" value="<%= @album.itunes_url %>">
<input type="hidden" id="url-youtube" value="<%= @album.youtube_url %>">
<input type="hidden" id="url-soundcloud" value="<%= @album.soundcloud_url %>">

  <div id="full-layer-image">
    <div class="container text-white">
      <div class="row music-image">
        <div class="col-md-4 offset-md-4 bg-dark">
          <div class="row justify-content-center">
            <img class="link-image" width="350" height="350" src="<%= @album.image_url %>" alt="">
          </div>
        </div>
      </div>
      <div class="row link-header-track">
        <div class="col-md-4 offset-md-4 pt-2 bg-dark">
          <div class="row justify-content-center text-center text-break">
            <h3 class="col-12"><%= @album.album_name %></h3>
            <h5 class="col-12 text-white-50"><%= @album.artist_name %></h5>
          </div>
        </div>
      </div>
      <div class="row link-player-wrap">
        <div class="col-md-4 offset-md-4 bg-dark">
          <div class="row justify-content-center">
            <iframe id="embed" class="mt-3"
              src="https://open.spotify.com/embed/album/<%= @album.album_id %>"
              width="400" height="200" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
          </div>
        </div>
      </div>
      <div class="row link-wrap">
        <div class="col-md-4 offset-md-4 bg-dark">
          <div class="row spotify-link-options border-bottom border-secondary">
            <%= link_to (@album.spotify_url), class: 'col' do %>
            <div class="col col-lg-12 col-sm-12 link-option-row">
              <div class="row align-items-center">
                <div class="col col-lg-9 col-sm-9 col-med-9 link-option-row-logo">
                   <img class="link-image" width="120" height="30" src="<%= asset_path "spotify.png" %>" alt="">
                </div>
                <div class="ccl col-lg-3 col-sm-3 col-med-3 link-option-row-play">
                  <p class="pt-2 text-white">Play</p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <div class="row itunes-link-options border-bottom border-secondary">
            <%= link_to (@album.itunes_url), class: 'col' do %>
            <div class="col col-lg-12 col-sm-12 link-option-row">
              <div class="row align-items-center">
                <div class="col col-lg-9 col-sm-9 col-med-9 link-option-row-logo">
                  <img class="link-image" width="120" height="30" src="<%= asset_path "apple_music.png" %>" alt="">
                </div>
                <div class="ccl col-lg-3 col-sm-3 col-med-3 link-option-row-play">
                  <p class="pt-2 text-white">Play</p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <div class="row youtube-link-options border-bottom border-secondary">
            <%= link_to (@album.youtube_url), class: 'col' do %>
            <div class="col col-lg-12 col-sm-12 link-option-row">
              <div class="row align-items-center">
                <div class="col col-lg-9 col-sm-9 col-med-9 link-option-row-logo">
                  <img class="link-image" width="120" height="30" src="<%= asset_path "youtube.png" %>" alt="">
                </div>
                <div class="ccl col-lg-3 col-sm-3 col-med-3 link-option-row-play">
                  <p class="pt-2 text-white">Play</p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <div class="row soundcloud-link-options">
            <%= link_to (@album.soundcloud_url), class: 'col' do %>
            <div class="col col-lg-12 col-sm-12 link-option-row">
              <div class="row align-items-center">
                <div class="col col-lg-9 col-sm-9 col-med-9 link-option-row-logo">
                  <img class="link-image" width="120" height="30" src="<%= asset_path "soundcloud.png" %>" alt="">
                </div>
                <div class="ccl col-lg-3 col-sm-3 col-med-3 link-option-row-play">
                  <p class="pt-2 text-white">Play</p>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <footer class="row justify-content-center mt-3 text-white-50">
        <p>Copyright &copy; 2021 Shinnosuke Akashi</p>
      </footer>
    </div>
  </div>

app/views/homes/top.html.erb
<div class="d-flex h-100 text-center text-white bg-dark">

  <div class="cover-container w-100 h-100 p-3 mx-auto flex-column align-top">
    <header class="mb-auto">
    </header>

    <main class="px-3">
        <!--各音楽プラットフォームの楽曲URLフォーム-->
      <div class="input-form">
        <h1>Listen Link</h1>
        <p class="lead"> リリースする楽曲のURLを1つにまとめましょう。</p>

        <!-- [エラーメッセージ] デフォルトで非表示。jQueryで表示される。-->
        <div class="error alert alert-danger d-none" role="alert"></div>

        <!-- ローディングアニメーション -->
        <div class="spinner-border text-light d-none" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      <% if user_signed_in? %>
        <form class="mt-4">
          <div class="row border p-2 border-secondary rounded">
            <img class="col-3 link-image" width="120" height="30" src="<%= asset_path "spotify.png" %>" alt="">
            <input type="text" id="albumUrl" class="col-7 form-control" placeholder="SpotifyのアルバムURLを入力してください。">
            <textarea id="spotify_sample" class="">https://open.spotify.com/album/7DIk8e5o3lUWJOHIPrzeAs?highlight=spotify:track:4uEvkDZ3AS4XRGFSW9LfxA</textarea>
            <button class="spotify-clipboard-btn btn-sm btn-secondary col-2" type="button" data-clipboard-action="copy" data-clipboard-target="#spotify_sample">
              <i class="fab fa-spotify"></i> Sample
            </button>
          </div>
          <div class="row border p-2 border-secondary">
            <img class="col-3 link-image" width="120" height="30" src="<%= asset_path "apple_music.png" %>" alt="">
            <input type="text" id="input_itunes_url" class="col-7 form-control" placeholder="Apple MusicのアルバムURLを入力してください。">
            <textarea id="itunes_sample" class="">https://music.apple.com/jp/album/get-the-strap/1503398799?i=1503398802</textarea>
            <button class="itunes-clipboard-btn btn-sm btn-secondary col-2" type="button" data-clipboard-action="copy" data-clipboard-target="#itunes_sample">
              <i class="fab fa-itunes-note"></i> Sample
            </button>
          </div>
          <div class="row border p-2 border-secondary">
            <img class="col-3 link-image" width="120" height="30" src="<%= asset_path "youtube.png" %>" alt="">
            <input type="text" id="input_youtube_url" class="col-7 form-control" placeholder="YoutubeのアルバムURLを入力してください。">
            <textarea id="youtube_sample" class="">https://www.youtube.com/watch?v=sXuIfZzyLrM</textarea>
            <button class="youtube-clipboard-btn btn-sm btn-secondary col-2" type="button" data-clipboard-action="copy" data-clipboard-target="#youtube_sample">
              <i class="fab fa-youtube"></i> Sample
            </button>
          </div>
          <div class="row border p-2 border-secondary">
            <img class="col-3 link-image" width="120" height="30" src="<%= asset_path "soundcloud.png" %>" alt="">
            <input type="text" id="input_soundcloud_url" class="col-7 form-control" placeholder="SoundcloudのアルバムURLを入力してください">
            <textarea id="soundcloud_sample" class="">https://soundcloud.com/groupchatrecordings/duckworthsound-x-shiso-get-the-strap-original-mix</textarea>
            <button class="soundcloud-clipboard-btn btn-sm btn-secondary col-2" type="button" data-clipboard-action="copy" data-clipboard-target="#soundcloud_sample">
              <i class="fab fa-soundcloud"></i> Sample
            </button>
          </div>
          <button class="w-50 mt-3 btn btn-lg btn btn-secondary" id="submit" type="button">Create Link</button>
        </form>
      </div>
      <!--APIを叩いて取得した各データをAlbumテーブルに保存-->
      <%= form_with model: @album, url: albums_path, method: :post, local: true do |f| %>
      <div class="hidden-form d-none">
        <%= f.hidden_field :album_id, class: 'album_id' %>
        <%= f.hidden_field :spotify_url, class: 'spotify_url' %>
        <%= f.hidden_field :album_name, class: 'album_name' %>
        <%= f.hidden_field :artist_name, class: 'artist_name' %>
        <%= f.hidden_field :image_url, class: 'image_url' %>
        <%= f.hidden_field :itunes_url, class: 'itunes_url' %>
        <%= f.hidden_field :youtube_url, class: 'youtube_url' %>
        <%= f.hidden_field :soundcloud_url, class: 'soundcloud_url' %>
      <!--リンク作成ボタンを押した後、再確認ボタンを表示-->
        <h4>こちらでよろしいでしょうか？</h4>
        <%= f.submit "URLを作成", class: 'w-25 mt-3 btn btn-lg btn btn-secondary' %>
        <%= link_to('やり直す', 'javascript:void(0);', onclick: "window.location.reload();", class: "w-25 mt-3 btn btn-lg btn btn-secondary")  %>
      </div>
      <% end %>
      <!-- APIコール後のデータ結果 -->
      <div class="results d-none">
        <div class="metadata"></div>
        <iframe id="embed" class="mt-3" src="" width="300" height="200" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
      </div>
    </main>
      <% else %>
      <!--ログインユーザー以外に表示-->
      <%= link_to "はじめる", new_user_registration_path, class: 'w-25 mt-3 btn btn-lg btn btn-secondary' %>
      <%= link_to "ログイン", new_user_session_path, class: 'w-25 mt-3 ml-3 btn btn-lg btn btn-secondary' %>
      <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'w-80 mt-3 ml-3 btn btn-lg btn btn-secondary' %>
      <% end %>

    <footer class="mt-auto text-white-50">
      <p>Copyright &copy; 2021 Shinnosuke Akashi</p>
    </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListenLink</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark border-bottom border-secondary" id="main-nav">
      <div class="container">
        <%= link_to "Listen Link", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "ホーム", root_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", my_page_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, class: 'nav-link', method: :delete %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>

    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% key = "success" if key == "notice" %>
          <% key = "error" if key == "alert" %>
          toastr['<%= key %>']('<%= value %>');
        <% end %>
      </script>
    <% end %>
  </body>

</html>

app/views/users/_index.html.erb
<table class='table text-white'>
  <thead>
    <tr>
      <th>アートワーク</th>
      <th>曲名</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><img class="link-image" width="50" height="50" src="<%= album.image_url %>" alt=""></td>
        <td><%= album.album_name %></td>
        <td><%= link_to 'Show', album_path(album), class: "text-white album_#{album.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class="row profile-wrap">
  <tr><%= attachment_image_tag user, :profile_image_id, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %></tr>
  <tr>
    <th>ユーザー名 : </th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>プロフィール</th>
  </tr>
  <tr>
    <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <!--<= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>-->
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<!--<div class="conainer pt-3 bg-dark text-white bg-dark">-->
<!--  <div class="d-flex row mypage-wrap">-->
<!--    <div class="align-self-start col col-sm-12 col-md-2 offset-md-1 border border-secondary rounded">-->
<!--      <h2>アーティスト情報</h2>-->
<!--      <= render 'info', user: @user %>-->
<!--    </div>-->
<!--    <div class="col col-sm-12 col-md-7 offset-md-1 border border-secondary rounded" style="border:1px solid #333">-->
<div class="conainer pt-3 bg-dark text-white bg-dark">
  <div class="d-flex row mypage-wrap">
    <div class="col-md-6 offset-md-3  border border-secondary rounded" style="border:1px solid #333">
      <h2 class="p-2">リンク一覧</h2>
      <%= render 'index', albums: @albums %>
    </div>
  </div>
  <footer class="row justify-content-center mt-3 text-white-50">
    <p>Copyright &copy; 2021 Shinnosuke Akashi</p>
  </footer>
</div>